Update slurm jobscript

diff --git a/scripts/jobmon_slurm b/scripts/jobmon_slurm
--- a/scripts/jobmon_slurm
+++ b/scripts/jobmon_slurm
@@ -59,53 +59,75 @@ function KMS_slurm() {
         local GPUS_PER_NODE="${BASH_REMATCH[2]}"
     fi
 
+    # Escape job name (JSON)
+    local JOB_NAME="${SLURM_JOB_NAME}"
+    JOB_NAME="${JOB_NAME//'\'/'\\'}"
+    JOB_NAME="${JOB_NAME//'"'/'\"'}"
+
     # Send information
     local API_URL="http://backend:3000/api"
     local X_AUTH_TOKEN="Bearer <API_TOKEN>"
 
-
     # decide whether start or stop event
+    local    CURL_OUT
+    local -i CURL_RET
     if   [[ "${SLURM_SCRIPT_CONTEXT}" == prolog_slurmctld ]]; then
-        curl -X 'PUT' \
-            "${API_URL}/job_start" \
-            --cookie "Authorization=${X_AUTH_TOKEN}" \
-            -d "{
-                   \"Id\": ${SLURM_JOB_ID},
-                   \"userName\": \"${SLURM_JOB_USER}\",
-                   \"userId\": ${SLURM_JOB_UID},
-                   \"groupName\": \"${SLURM_JOB_GROUP}\",
-                   \"groupId\": ${SLURM_JOB_GID},
-                   \"account\": \"${SLURM_JOB_ACCOUNT}\",
-                   \"jobName\": \"${SLURM_JOB_NAME}\",
-                   \"clusterId\": \"${SLURM_CLUSTER_NAME}\",
-                   \"partition\": \"${SLURM_JOB_PARTITION}\",
-                   \"numNodes\": ${NUM_NODES},
-                   \"numTasks\": ${NUM_TASKS},
-                   \"tasksPerNode\": ${TASKS_PER_NODE},
-                   \"GPUsPerNode\": ${GPUS_PER_NODE},
-                   \"startTime\": $(date +%s) ,
-                   \"nodeList\": \"${NODELIST_CSV}\",
-                   \"isRunning\": true,
-                   \"jobScript\": \"noJobSript\",
-                   \"projectId\": \"noProject\"
-               }"
+        CURL_OUT=$(
+            curl -X 'PUT' \
+                "${API_URL}/job_start" \
+                --max-time 10 \
+                --silent \
+                --show-error \
+                --cookie "Authorization=${X_AUTH_TOKEN}" \
+                -d "{
+                       \"Id\": ${SLURM_JOB_ID},
+                       \"userName\": \"${SLURM_JOB_USER}\",
+                       \"userId\": ${SLURM_JOB_UID},
+                       \"groupName\": \"${SLURM_JOB_GROUP}\",
+                       \"groupId\": ${SLURM_JOB_GID},
+                       \"account\": \"${SLURM_JOB_ACCOUNT}\",
+                       \"jobName\": \"${JOB_NAME}\",
+                       \"clusterId\": \"${SLURM_CLUSTER_NAME}\",
+                       \"partition\": \"${SLURM_JOB_PARTITION}\",
+                       \"numNodes\": ${NUM_NODES},
+                       \"numTasks\": ${NUM_TASKS},
+                       \"tasksPerNode\": ${TASKS_PER_NODE},
+                       \"GPUsPerNode\": ${GPUS_PER_NODE},
+                       \"startTime\": $(date +%s) ,
+                       \"nodeList\": \"${NODELIST_CSV}\",
+                       \"isRunning\": true,
+                       \"jobScript\": \"noJobSript\",
+                       \"projectId\": \"noProject\"
+                 }" 2>&1
+        )
+        CURL_RET="$?"
     elif [[ "${SLURM_SCRIPT_CONTEXT}" == epilog_slurmctld ]]; then
-        curl -X 'PATCH' \
-            "${API_URL}/job_stop/${SLURM_JOB_ID}" \
-            --cookie "Authorization=${X_AUTH_TOKEN}" \
-            -d "{
-                    \"exitCode\": ${SLURM_JOB_EXIT_CODE},
-                    \"stopTime\": $(date +%s)
-                }"
+        CURL_OUT=$(
+            curl -X 'PATCH' \
+                "${API_URL}/job_stop/${SLURM_JOB_ID}" \
+                --max-time 10 \
+                --silent \
+                --show-error \
+                --cookie "Authorization=${X_AUTH_TOKEN}" \
+                -d "{
+                        \"exitCode\": ${SLURM_JOB_EXIT_CODE},
+                        \"stopTime\": $(date +%s)
+                    }" 2>&1
+        )
+        CURL_RET="$?"
     else
         return 1
     fi
-}
 
-COMMAND_LINE_PARAMETER=( "$@" )
+    if [[ ${CURL_RET} -ne 0 ]]; then
+        logger --tag "jobmon_slurm" "${CURL_OUT}"
+    fi
+}
 
 KMS_slurm
 
 # Cleanup
 unset KMS_slurm
-unset COMMAND_LINE_PARAMETER
+
+# Avoid slurm job submission errors
+exit 0
